# Generated by Django 4.2 on 2025-12-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('PEN', 'Soles (PEN)'), ('USD', 'Dólares (USD)')], default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('YAPE', 'Yape'), ('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('OTRO', 'Otro')], default='YAPE', max_length=14),
        ),
    ]
